SciML/RecursiveArrayTools.jl

README.md, src/RecursiveArrayTools.jl, src/array_partition.jl, src/vector_of_array.jl, test/basic_indexing.jl, test/interface_tests.jl, test/runtests.jl
Let me know what you need. My gitfu is weak.
=> Add code that gives an nice Array interface to a vector of arrays

src/array_partition.jl, test/partitions_test.jl
When I tried to use `ArrayPartitions` I discovered https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/issues/11 and the closed issue https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/issues/8 about type instabilities. However, there are still many type instabilities left - e.g. results of `zeros(x)`, `last(x)`, and all vector space operations such as multiplication and addition can not be inferred. Moreover, not in-place broadcasting does only work if the types are not changed by the applied function, as noted in https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/issues/11.
Hence I tried to improve `ArrayPartition` and fix most of these things. This PR should fix https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/issues/11 (all broadcasts should work in a type-stable fashion) …
=> Improved ArrayPartition

src/utils.jl, test/copy_static_array_test.jl, test/runtests.jl
`recursivecopy!`now uses `copy` for `StaticArray`s, see #19. This should be correct for both mutable and immutable `StaticArray`s, but performance could probably be improved for mutable ones if `copy!` can be used.
Could you please release a new version `v0.12.2` of `RecursiveArrayTools` including this fix?
=> recursivecopy! for StaticArrays

src/utils.jl, test/copy_static_array_test.jl, test/runtests.jl
This fixes some problems for OrdinaryDiffEq with callbacks if `u <: StaticArray`.
=> fix copyat_or_push! for StaticArrays

src/vector_of_array.jl
This PR causes "matrix getindex" with a colon in the first place to return the unmodified underlying AbstractVector. Tests pass, bu I can potentially imagine unexpected behaviour if the internal AbstractArray is multidimensional. If problems like these are sorted out, I think it's nice to be able to get back, e.g., an `SVector` without having it converted to a standard `Array`
```julia
julia> using RecursiveArrayTools, StaticArrays
julia> s1 = SVector(1,2);
julia> s2 = SVector(3,4);
julia> a = VectorOfArray([s1,s2])
VectorOfArray{Int64,2}
u:
2-element Array{SVector{2,Int64},1}:
[1, 2]
[3, 4]
julia> a[:,2]
2-element Array{Int64,1}:
3
4
julia> a[:,2]
2-element SVector{2,Int64}:
3
4
```
=> Add getindex(::VofA, ::Colon, ::Int)

src/vector_of_array.jl, test/interface_tests.jl
This PR is addressing #23.
I've added dispatch on VectorOfArray for Base.similar
I didn't do it for DiffEqArray. As I understand, DiffEqArray is used to store the results, so do we really need to use similar with it?
I've added dispatch on AbstractVectorOfArray for Base.fill!
For DiffEqArray it ignores ts and just fills u.
Now we can use zeros and ones with VectorOfArray.
I also fixed any(f, itr) for AbstractVectorOfArray. Now ODE_DEFAULT_UNSTABLE_CHECK from DiffEqBase works properly with AbstractVectorOfArray.
I suppose I should have done separate PR for it, but the change is small.
=> Base.similar and Base.fill! for VectorOfArray

src/array_partition.jl, test/partitions_test.jl
I think we can do away with must of the generated functions,
but as they say the proof is in pudding.
Chris, is there a set of benchmarks I should test this against?
=> [WIP] Rework broadcast

src/utils.jl
As discussed in https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/95#discussion_r249277410. Tests with Measurements.jl in PuMaS still succeed. Is there anything else that should be tested prior to merging?
=> No deep copy for numbers

src/utils.jl, test/utils_test.jl
Before the `recursive_bottom_eltype` function was written with only
numeric types in mind. For those, it worked. But for non-numeric types
it recused infinitely, causing a `StackOverflowError`.
Now it works on any type and is sure to recurse only a finite number of
time, thus always end and return a result.
The recursion ends, when the given argument `a` is the same as `eltype(a)`. So, as there is a limited amount of types in Julia, we will only recurse a limited amount of times.
I also added tests that cover this specific function, testing numbers
with and without units as well as chars and strings.
=> Type agnostic, finite recursive_bottom_eltype function

test/utils_test.jl
While working on #55 I noticed, that the tests for the
`recursive_unitless_eltype` function are not actually run. They are
written down, but without a `@test` macro their result are never
checked. So I added the macro.
=> Actaully test `recursive_unitless_eltype`

Project.toml, src/RecursiveArrayTools.jl, src/zygote.jl
Since getindex on 1D acts differently than it usually does for a matrix, we need to fix the type on the output.
=> add some Zygote rules

.travis.yml, Project.toml, src/RecursiveArrayTools.jl, src/array_partition.jl, test/partitions_test.jl, test/runtests.jl, test/upstream.jl
Should get improved, but the general idea. The hard part for the stiff ODE solvers seems to be the broadcast
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/71 Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/67 Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/60 Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/44
=> support linear algebra on ArrayPartition

Project.toml, src/array_partition.jl, test/partitions_test.jl
```julia
using RecursiveArrayTools, BenchmarkTools
xce0 = ArrayPartition(zeros(2),[0.])
xcde0 = copy(xce0)
function foo(y, x)
y .= y .+ 2 .* x
end
@btime foo($xcde0, $xce0)
```
```
19.075 ns (0 allocations: 0 bytes)
```
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/72 
@rveltz
=> fix broadcast allocations

src/vector_of_array.jl, test/basic_indexing.jl
Relies on Julia's v1.5 `@view` optimizations to be super fast, but the main reason for this is because it's more correct on ragged arrays. However, it's currently hitting a weird problem:
```julia
[ Info: Precompiling RecursiveArrayTools [731186ca-8d62-57ce-b412-fbd966d074cd]
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6690ec5e -- jl_subtype_env at /cygdrive/d/buildbot/worker/package_win64/build/src\subtype.c:1800
in expression starting at none:0
jl_subtype_env at /cygdrive/d/buildbot/worker/package_win64/build/src\subtype.c:1800
jl_subtype at /cygdrive/d/buildbot/worker/package_win64/build/src\subtype.c:1854 [inlined]
jl_isa at …
```
=> AbstractVectorOfArray broadcast overload

Project.toml, src/array_partition.jl, test/upstream.jl
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/105 Previous test cases only handled vectors, so it just took a few `vec`s
=> Handle and test ArrayPartition linear algebra over Arrays

Project.toml, src/zygote.jl, test/adjoints.jl, test/runtests.jl, test/utils_test.jl
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/111
=> add some more adjoints and test adjoints

Project.toml
If tests pass, there should be a new release of RecursiveArrayTools.jl since it holds back updates for NonlinearSolve.jl (https://github.com/JuliaComputing/NonlinearSolve.jl/pull/16) and DiffEqBase.jl (SciML/DiffEqBase.jl#604) which in turns hold back updates for a lot of downstream packages.
This needs a new release of OrdinaryDiffEq.jl.
=> bump compat version bounds

src/array_partition.jl, test/partitions_and_static_arrays.jl
Fixed the determination of eltype of ArrayPartition in the case of complex nested arrays, such as vectors of StaticArrays, for example.
Fixes #125
=> Fixes #125

src/zygote.jl
Computing the adjoint of a `SecondOrderODEProblem` requires an adjoint for this constructor because of the following line.
https://github.com/SciML/DiffEqBase.jl/blob/9f0875ad24ac9c2f5784b242eba5344807f278e7/src/problems/ode_problems.jl#L153
This PR depends on FluxML/ZygoteRules.jl#12 because of the anonymous value type argument. That was a fun one to debug :)
=> Define the custom adjoint on a more general ArrayPartition constructor

.gitignore, src/array_partition.jl, test/partitions_test.jl
A `PartitionedArray` should be considered "mutable" only, if all of its components are "mutable".
Therefore the `ArrayInterface.ismutable` has been specialized for this case.
This fixes a bug in https://github.com/SciML/OrdinaryDiffEq.jl/issues/1322
Another question is the naming `ArrayInteface.ismutable` which collides with `Base.ismutable` and returns different results.
=> fix ArrayInterface.ismutable(::ArrayPartition)

src/array_partition.jl
- Adds an `any` method without predicate. Needed for efficiently calling `any` on e.g. `ArrayPartition{Float32, Tuple{CuArray{Float32, 1}, CuArray{Float32, 1}}}`
- Adds analogous `all` methods.
=> Add more specialized functions

src/array_partition.jl, test/partitions_test.jl
It would be useful to allow a custom AbstractArray type inside an ArrayPartition to be preserved during broadcasting, but currently it is not. Understandably, one needs to extend some of the broadcasting functions to the new type, as I show below. However, there is a small fix needed to the package to enable this. This is because `unpack`, which strips out each partition one by one and creates a separate `Broadcasted` wrapper for it, gives the same promoted `BroadcastStyle` to each one, even if they are different types, so some get dispatched to the wrong `similar` function in `copy`. In the PR, I don't pass the `Style` during the unpack to allow it to decide naturally which style it is. 
If you'd like further detail, for example, consider
```
struct MyType{T} <: AbstractVector{T}
data :: …
```
=> Preserve custom AbstractArray types during broadcasting of ArrayPartition

src/array_partition.jl, test/partitions_test.jl
Hot fix to #137 
The original issue lies in the way broadcasting works for `zeros()`, since `zeros().+2.0` gets turned from `Array{Float64, 0}` into `Float64`, because apparently that is how broadcasting is set up for `DefaultArrayStyle{0}` (This seems like a bug in Julia.) Before #136, this wasn't a problem for broadcasting of `ArrayPartition` as long as an `Array{Float64, 0}` was paired with another component of higher `Array` rank, e.g., `ap = ArrayPartition(zeros(),[1.0])`, since they would all be broadcast via `DefaultArrayStyle{1}` rules. So `ap+1.0` would be of the same type as `ap`. But on its own, e.g., `ap = ArrayPartition(zeros())`, then `ap + 1.0` would *not* be the same type as `ap`, since it gets broadcast as a `DefaultArrayStyle{0}`. Unfortunately, #136 exposed this issue. …
=> Allow DefaultArrayStyle to be broadcast according to normal rules

Project.toml, src/utils.jl, test/copy_static_array_test.jl
As discussed in https://github.com/SciML/OrdinaryDiffEq.jl/issues/1386 and suggested by @ChrisRackauckas.
Closes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1386
=> fix recursivecopy

src/array_partition.jl, test/partitions_test.jl
Specialized `map` method over a single `ArrayPartition` to close #140.
=> Faster `map` over `ArrayPartition`s.

Project.toml, src/RecursiveArrayTools.jl, src/vector_of_array.jl, test/downstream/Project.toml, test/downstream/symbol_indexing.jl, test/runtests.jl
This PR is required for https://github.com/SciML/SciMLBase.jl/pull/66 and does the following:
=> Enable symbol based indexing of interpolated solutions by adding extra fields to DiffEqArray type

src/vector_of_array.jl
Fixes #146 
CC: @ChrisRackauckas
=> Fix for #146

src/vector_of_array.jl, test/basic_indexing.jl, test/interface_tests.jl
Required for https://github.com/SciML/SciMLBase.jl/pull/66
=> Add special cases for DiffEqArray constructor

src/zygote.jl
See [ModelingToolkit #972](https://github.com/SciML/ModelingToolkit.jl/issues/972).
=> Prevent this rule from being misapplied to `Symbol` types. 

src/vector_of_array.jl
Pushing to `AbstractVectorOfArray` is currently limited to vectors with eltype `AbstractVector`, which seems likely to have been a too-restrictive oversight. This PR broadens the accepted eltype to `AbstractArray`.
=> Broaden vector eltype signature for `push!`

src/zygote.jl
I didn't notice it but there was another case where you can get symbolic values where the `ZygoteRule` expects integers.  In this case, it happened when I was trying out parameter passing as `LabelledArrays`.
=> Fix for another instance of the same kind of issue as #151.

src/vector_of_array.jl
https://github.com/SciML/ModelingToolkit.jl/issues/1102#issuecomment-876130158
@baggepinnen  This is great!
Old:
```
BechmarkTools.Trial: 10000 samples with 6 evaluations.
Range (min … max):  5.215 μs … 467.285 μs  ┊ GC (min … max): 0.00% … 98.36%
Time  (median):     5.382 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   5.521 μs ±   6.023 μs  ┊ GC (mean ± σ):  1.53% ±  1.39%
▁▃▅██▇▅▄▂▁                                                  ▂
█████████████▇██▇▇▇▆▄▆▃▆▅▃▃▄▁▅▄▄▃▄▁▃▃▁▅▁▃▃▃▁▃▄▃▄▁▄▄▅▄▁▄▃▃▄▃ █
5.22 μs      Histogram: log(frequency) by time      7.47 μs <
Memory estimate: 1.53 KiB, allocs estimate: 35.
```
New:
```
BechmarkTools.Trial: 10000 samples with 109 evaluations.
Range (min … max):  769.495 ns …  20.644 μs  ┊ GC (min … max): 0.00% … 95.35%
Time  (median): …
```
=> Improve issymbollike performance

src/vector_of_array.jl, test/utils_test.jl
```julia
julia> @variables x;
julia> @btime issymbollike(Ref($x)[])
0.026 ns (0 allocations: 0 bytes)
true
julia> @btime issymbollike(Ref(1)[])
0.026 ns (0 allocations: 0 bytes)
false
julia> @btime issymbollike(Ref(:x)[])
0.026 ns (0 allocations: 0 bytes)
true
```
=> Optimize issymbollike

src/vector_of_array.jl, test/downstream/symbol_indexing.jl
https://github.com/SciML/SciMLBase.jl/issues/83
=> Remove unreachable code

src/array_partition.jl, test/partitions_test.jl
This is the first batch of changes related to #160 . Most changes are related to the fact that `map` is much more friendly to Julia compiler than broadcasting so I've replaced a bunch of unnecessary broadcasts with `map`. The other thing is that the loop in assignment broadcast is very problematic -- ideally compiler should be able to constant-propagate `N` and unroll the loop but it seems that doing so breaks some other optimizations. This change helps a bit but it's still not enough.
=> Speed up some use cases of `ArrayPartition`

src/RecursiveArrayTools.jl, src/array_partition.jl, src/vector_of_array.jl
Need https://github.com/SciML/ResettableStacks.jl/pull/15 and https://github.com/JuliaRandom/RandomNumbers.jl/pull/79
They are required to make the printing round-trip-able
```julia
julia> W = WienerProcess(1,2,3)
t: 1-element Vector{Int64}:
1
u: 1-element Vector{Int64}:
2
julia> show(W)
NoiseProcess{Int64, 1, Int64, Int64, Int64, Vector{Int64}, typeof(DiffEqNoiseProcess.WHITE_NOISE_DIST), typeof(DiffEqNoiseProcess.WHITE_NOISE_BRIDGE), false, ResettableStack{Tuple{Int64, Int64, Int64}, false}, ResettableStack{Tuple{Int64, Int64, Int64}, false}, RSWM{Float64}, Nothing, RandomNumbers.Xorshifts.Xoroshiro128Plus}(DiffEqNoiseProcess.WHITE_NOISE_DIST, DiffEqNoiseProcess.WHITE_NOISE_BRIDGE, [1], [2], [2], [3], 1, 2, 3, 1, 2, 3, 2, 3, 2, 3, ResettableStack{Tuple{Int64, Int64, Int64}, …
```
=> Round-trip printing

src/zygote.jl
This is inspired by https://github.com/SciML/DiffEqSensitivity.jl/pull/493#issuecomment-927014502 . I wrote many examples there, but the core surprise was that a `VectorOfArrays{T} <: AbstractArray{T,3}` has a gradient `Vector{Matrix{T}}` which is not a 3-array. If I understood correctly, it would desirable that the result be another VectorOfArray, i.e. something `AbstractArray{T,3}` which iterates like Vector{Matrix}.
One way to do that would be using ProjectTo. But in fact I believe the Vector{Matrix} is being explicitly generated by a rule defined here, so perhaps it is simpler just to alter that rule to wrap this?
RFC, WIP, needs tests... and needs thought about other cases:
```julia
julia> va = RecursiveArrayTools.VectorOfArray([rand(3,3), rand(3,3)]);
julia> gradient(va -> …
```
=> Gradient definitions & supertypes

src/utils.jl
Addresses https://github.com/SciML/ModelingToolkit.jl/issues/1353
The problem in the linked issue is not solved completely since the eltype infers to `Any`, but this PR prevents the stackoverflow.
=> Provide base case for recursive eltype functions

src/vector_of_array.jl, test/gpu/vectorofarray_gpu.jl
=> Specialize getindex for indexing VectorOfArray with mask and colon

src/array_partition.jl, test/partitions_test.jl
=> Fix shaped similar for ArrayPartition

src/array_partition.jl, test/partitions_test.jl
Without this custom method the inner `ArrayPartition` of a nested `ArrayPartition` is turned into a normal vector by unary minus.
=> Fix unary minus for nested ArrayPartition

Project.toml, src/RecursiveArrayTools.jl, src/array_partition.jl, src/utils.jl, test/partitions_test.jl, test/upstream.jl
Before and after:
```julia
julia> @time_imports using RecursiveArrayTools
10.7 ms    ┌ MacroTools
19.2 ms  ┌ ZygoteRules
2.8 ms  ┌ Compat
1.4 ms  ┌ Requires
123.4 ms  ┌ FillArrays
507.7 ms  ┌ StaticArrays
17.8 ms      ┌ Preferences
19.6 ms    ┌ JLLWrappers
184.0 ms  ┌ LLVMExtra_jll
5.1 ms      ┌ CEnum
108.6 ms    ┌ LLVM
1.9 ms    ┌ Adapt
804.4 ms  ┌ GPUArrays
5.8 ms  ┌ DocStringExtensions
1.3 ms  ┌ IfElse
39.8 ms  ┌ RecipesBase
40.6 ms    ┌ Static
504.1 ms  ┌ ArrayInterface
73.6 ms  ┌ ChainRulesCore
2332.6 ms  RecursiveArrayTools
julia> @time_imports using RecursiveArrayTools
10.1 ms    ┌ MacroTools
18.7 ms  ┌ ZygoteRules
2.6 ms  ┌ Compat
123.9 ms  ┌ FillArrays
521.7 ms  ┌ StaticArrays
18.4 ms      ┌ Preferences
20.2 ms    ┌ JLLWrappers
173.5 ms  ┌ LLVMExtra_jll
4.8 ms      ┌ CEnum
103.7 …
```
=> Only require ArrayInterfaceCore

src/array_partition.jl, test/partitions_and_static_arrays.jl
This only works for partition elements that themselves have a length-on-type function, e.g. SVector or SMatrix.
I'm trying to use this line of code from NearestNeighbors.jl (issue on the call `length(::Type{ArrayPartition...}})`:
https://github.com/KristofferC/NearestNeighbors.jl/blob/fb84d15b96a2d7f94f691db4ff6f42e994194c93/src/tree_data.jl#L14
MWE I'm working to fix:
```julia
using Manifolds, NearestNeighbors, Distances, StaticArrays
import Manifolds: ArrayPartition
Base.@kwdef struct DistSE2 <: Distances.Metric
M = SpecialEuclidean(2)
end 
(d::DistSE2)(p,q) = Manifolds.ManifoldsBase.distance(d.M,p,q)
pts = [ArrayPartition(SA[randn(2)...], SMatrix{2,2}([1 0; 0 1.])) for _ in 1:10]
dSE2 = DistSE2()
bt = NearestNeighbors.BallTree(pts, dSE2)
```
-----
```julia
julia> bt = …
```
=> Base.length dispatch for ArrayPartition (StaticArrays)

src/zygote.jl, test/adjoints.jl
Related issue: https://github.com/SciML/SciMLSensitivity.jl/issues/689
The reason why some ArrayPartition tests are working is that the `@code_typed` from Zygote uses the ZygoteRules
```julia
ZygoteRules.@adjoint function ArrayPartition(x::S, ::Type{Val{copy_x}} = Val{false}) where {S<:Tuple,copy_x}
function ArrayPartition_adjoint(_y)
y = Array(_y)
starts = vcat(0,cumsum(reduce(vcat,length.(x))))
ntuple(i -> reshape(y[starts[i]+1:starts[i+1]], size(x[i])), length(x)), nothing
end
ArrayPartition(x, Val{copy_x}), ArrayPartition_adjoint
end
```
The failing ones instead use the ChainRules definition
```julia
function ChainRulesCore.rrule(::Type{<:ArrayPartition}, x::S, ::Type{Val{copy_x}} = Val{false}) where {S<:Tuple,copy_x}
function ArrayPartition_adjoint(_y)
y = Array(_y)
starts = …
```
=> Differentiating ArrayPartitions in DEProblems

Project.toml, src/RecursiveArrayTools.jl, src/tabletraits.jl, test/downstream/symbol_indexing.jl, test/runtests.jl, test/tabletraits.jl, test/testutils.jl
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/211. With this PR, the example in the issue works as expected:
```julia
julia> using OrdinaryDiffEq, DataFrames
julia> f_2dlinear = (du,u,p,t) -> du.=1.01u;
julia> prob = ODEProblem(f_2dlinear,rand(2,2),(0.0,1.0));
julia> sol1 =solve(prob,Euler();dt=1//2^(4));
julia> df = DataFrame(sol1)
17×5 DataFrame
Row │ timestamp  value1    value2    value3     value4   
│ Float64    Float64   Float64   Float64    Float64  
─────┼────────────────────────────────────────────────────
1 │    0.0     0.494427  0.12895   0.0152497  0.330754
2 │    0.0625  0.525638  0.13709   0.0162124  0.351633
3 │    0.125   0.558819  0.145744  0.0172358  0.373829
4 │    0.1875  0.594094  0.154944  0.0183238  0.397427
5 │    0.25    0.631596  0.164724 …
```
=> Implement table traits for DiffEq arrays

src/array_partition.jl, test/partitions_test.jl
Because ArrayPartition is an AbstractVector but allows a non-square indexing scheme, this confuses the defaults and thus this requires a specialization. Fixes https://github.com/SciML/RecursiveArrayTools.jl/pull/239
=> Fix (colon,j...) indexing of ArrayPartition

.JuliaFormatter.toml, Project.toml, src/vector_of_array.jl, test/symbolic_indexing_interface_test.jl
=> Fix symbol indexing by checking that observed !== nothing

Project.toml, src/RecursiveArrayTools.jl, src/array_partition.jl, src/vector_of_array.jl, test/runtests.jl
@AayushSabharwal I'm trying to see if adding `::NTuple{N, Int}` is a valid signature on `DiffEqArray`.
Having `::NTuple{N}` in the third position is compatible with `NTuple{N,Symbol}`, resulting in ambiguities with the following two constructors.
This is an attempt to avoid that ambiguity, while being totally ignorant of what that third argument in the first constructor is actually supposed to be.
=> Ambiguity errors and format

src/utils.jl, test/utils_test.jl
This PR fixes `recursivefill!` when attempting to fill a `VectorOfArray` in which the element type is some sort of `StaticArray`.
Here is a minimal example:
```julia
using RecursiveArrayTools
using StaticArrays
A = VectorOfArray([randn(SVector{3, Float64}, i) for i ∈ 1:4])   # A[i] is a Vector{SVector{...}}
B = recursivecopy(A)
recursivefill!(B, zero(eltype(B)))
C = recursivecopy(A)
recursivefill!(C, false)
```
In the current master, the calls to `recursivefill!` respectively fail with:
```julia
1. ERROR: MethodError: Cannot `convert` an object of type Float64 to an object of type SVector{3, Float64}                                                                                                           
2. ERROR: MethodError: no method matching fill(::Bool, ::Type{Vector{SVector{3, …
```
=> Fix `recursivefill!` for `VectorOfArray{<:StaticArray}`

src/vector_of_array.jl
Improves the error message in #271.
=> fix UndefVarError: `_throw_dmrs` not defined

src/array_partition.jl, test/partitions_test.jl, test/runtests.jl
Fix #275 
Seems like it was ok to just remove all type constraints. I did a quick check with a dummy array type and the performance was identical to current main.
~~I tried to do the same thing for `zero`, but then it would no longer infer (even with the same construction as in the example in #275). Since I don't seem to need it for my use case I just left it as is.~~
Also did the same for `zero` since it had the same type of issue.
The tests might seem a bit silly. I put it in a separate commit in case you don't want it.
=> Remove type constraints for copy of ArrayPartition

src/array_partition.jl, test/partitions_test.jl
This fixes #273 . Maybe not the most efficient but it is better than crashing.
=> Fix Cartesian indexing into ArrayPartition

Project.toml
https://github.com/SciML/RecursiveArrayTools.jl/pull/287 was actually a breaking change
=> Replace version 2.39.0 with version 3.0

src/vector_of_array.jl, test/interface_tests.jl
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/300
=> Add and test some missing interface functions

src/array_partition.jl, src/vector_of_array.jl
=> ci: fix infinite test

src/vector_of_array.jl, test/interface_tests.jl
=> fix: fix broadcasted assignment to VOA of StaticArrays

src/array_partition.jl, src/utils.jl, src/vector_of_array.jl, test/qa.jl, test/utils_test.jl
=> fix: add utils methods for AbstractVectorOfArray, fix method overwriting on 1.10

src/vector_of_array.jl, test/interface_tests.jl
=> feat: add ability to set VectorOfArray with Array using broadcast

src/vector_of_array.jl, test/interface_tests.jl
=> fix: allow setting VoA of SArray using scalars

src/vector_of_array.jl
=> fix: rework broadcasting copyto!

Project.toml, ext/RecursiveArrayToolsFastBroadcastExt.jl, src/RecursiveArrayTools.jl, src/vector_of_array.jl, test/interface_tests.jl
=> fix: add FastBroadcastExt for Vector of SArrays

src/vector_of_array.jl, test/linalg.jl
=> fix: add support for adjoint of AbstractVectorOfArray

ext/RecursiveArrayToolsZygoteExt.jl, src/utils.jl, test/adjoints.jl, test/downstream/symbol_indexing.jl
=> feat: add support for autodiff through broadcasting of VoA

src/utils.jl, test/utils_test.jl
=> fix: vecvecapply

ext/RecursiveArrayToolsZygoteExt.jl, src/array_partition.jl, src/vector_of_array.jl, test/adjoints.jl, test/interface_tests.jl, test/partitions_test.jl
=> fix: mapreduce type stability, VoA broadcast adjoints

src/array_partition.jl, src/vector_of_array.jl, test/interface_tests.jl, test/partitions_test.jl
=> fix: VoA stack, ArrayPartition arithmetic type stability

src/vector_of_array.jl, test/basic_indexing.jl
=> fix: add setindex! for higher dimensional VoA, fix checkbounds allocations

ext/RecursiveArrayToolsZygoteExt.jl, src/vector_of_array.jl
=> fix: remove linear indexing from getindex adjoints

src/vector_of_array.jl
=> fix: make Base method dispatches more abstract

src/vector_of_array.jl, test/interface_tests.jl
=> fix: fix views with boolean mask

.github/workflows/Downstream.yml, Project.toml, ext/RecursiveArrayToolsReverseDiffExt.jl, ext/RecursiveArrayToolsZygoteExt.jl, src/utils.jl, src/vector_of_array.jl
=> build: add SciMLSensitivity tests to downstream CI

src/vector_of_array.jl
This one shows up in ensemble plot recipes.
=> Fix deprecated indexing in `vecarr_to_vectors`

Project.toml, ext/RecursiveArrayToolsForwardDiffExt.jl, test/adjoints.jl
=> fix: implement ForwarDiff.extract_derivative for AbstractVectorOfArray

.github/workflows/CI.yml, .github/workflows/Documentation.yml, .github/workflows/Downstream.yml
Explicitly specify the codecov token to be used (i.e., `CODECOV_TOKEN`), given that the latest v4 release of the codecov action requires it to be able to generate coverage reports. Additionally, fail CI if coverage reporting fails, since coverage is an important enough metric for us to ensure that it's tracked consistently.
=> ci: explicitly specify token for codecov

src/array_partition.jl, test/partitions_test.jl
=> fix: fix inference of `getindex(::ArrayPartition, ::Int)`

src/vector_of_array.jl, test/basic_indexing.jl
Addresses https://github.com/SciML/OrdinaryDiffEq.jl/pull/2087#issuecomment-1934232736
=> Add support for `VectorOfArray(AbstractArray{<:AbstractArray})`

test/runtests.jl
=> test: separate SII-related tests into SII testset

ext/RecursiveArrayToolsZygoteExt.jl, test/downstream/symbol_indexing.jl
Allows for the handling of symbolic variables for indexing into solution objects
```julia
@parameters σ ρ β
@variables x(t) y(t) z(t) w(t)
eqs = [D(D(x)) ~ σ * (y - x),
D(y) ~ x * (ρ - z) - y,
D(z) ~ x * y - β * z,
w ~ x + y + z]
@mtkbuild sys = ODESystem(eqs, t)
ModelingToolkit.observed(sys)
u0 = [D(x) => 2.0,
x => 1.0,
y => 0.0,
z => 0.0]
p = [σ => 28.0,
ρ => 10.0,
β => 8 / 3]
tspan = (0.0, 100.0)
prob = ODEProblem(sys, u0, tspan, p, jac = true)
sol = solve(prob, Tsit5())
sol[sys.x]
```
=> Feat: Support for symbolic indexing of solution objects

src/vector_of_array.jl, test/basic_indexing.jl
Addresses https://github.com/SciML/RecursiveArrayTools.jl/issues/373
The fix just involves modifying `Base.copy` for `VectorOfArray` with multi-dimensional parent arrays. This could replace the old `Base.copy` implementation, but I left the old implementation there just in case it changes behavior upstream.
=> Fix multi-dimensional `VectorOfArray` broadcast

.github/workflows/CI.yml, .github/workflows/Documentation.yml, .github/workflows/FormatCheck.yml, .github/workflows/Invalidations.yml
Update the workflows in this repository to use SciML's reusable workflows.
This is part of a larger effort to standardise the SciML's CI workflows for more generic and common requirements, to keep the workflows uniform and easier to maintain.
=> ci: standardise workflows using SciML's reusable workflows

Project.toml, src/vector_of_array.jl, test/gpu/vectorofarray_gpu.jl
Needs testing.
Basically we can now use `convert(AbstractArray, x)` to do a device agnostic convert.
=> Device agnostic convert

ext/RecursiveArrayToolsZygoteExt.jl
The current rule does not account for the various Tangent types that can be seen when working with downstream packages (specifically note AD'ing through observable functions via SII). It is much better to remove the rule and let AD take care of picking out the right fields etc. If its preferred to retain the rule (to get the VectorOfArray type returned in the reverse pass), then we will need to handle that elsewhere. For now, let's check for breakages in CI.
=> Remove projection rule for `VectorOfArray`

ext/RecursiveArrayToolsZygoteExt.jl, test/adjoints.jl
=> fix: fix `Base.view` adjoints

ext/RecursiveArrayToolsReverseDiffExt.jl, ext/RecursiveArrayToolsZygoteExt.jl
=> fix: fix view adjoints

src/vector_of_array.jl, test/interface_tests.jl
=> feat: add `ndims` method for `::Type{<:AbstractVectorOfArray}`

src/array_partition.jl, test/partitions_test.jl
Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2182
=> Fix copyto! overload for arraypartitions of scalars

src/vector_of_array.jl, test/copy_static_array_test.jl
Fix #378.
The corner case was considered but was never included in tests, so the error was not caught during development.
=> Fix broadcast failure for `VectorOfArray` with `SVector{1}`

Project.toml, src/vector_of_array.jl
Relying on stack removes the need to `adapt`, which should make the GPUs more efficient. With `stack`, those extra dispatches were unnecessary. They were rarely hit and one had a bug too! So they can just be removed. Seems to fix downstream.
=> Simplify VectorOfArray indexing

src/vector_of_array.jl, test/interface_tests.jl, test/linalg.jl, test/partitions_test.jl
=> fix: do not assume `AbstractVectorOfArray` is mutable in `Base.zero`

Project.toml, ext/RecursiveArrayToolsStructArraysExt.jl, src/vector_of_array.jl, test/copy_static_array_test.jl
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/410
This specializes so that if `u.u` is not a vector, it will convert the broadcast to fix that. I couldn't find a nice generic way to use `map` so the fallback is to build the vector and convert, which seems to not be a big performance issue. For StructArrays, `convert(typeof(x), Vector(x))` fails, and so this case is specialized.
=> Fix StructArray broadcast in VectorOfArray

src/array_partition.jl, src/utils.jl, test/gpu/arraypartition_gpu.jl, test/runtests.jl
- [Tests Pass] Any code changes were done in a way that does not break public API
- [NA] All documentation related to code changes were updated
- [NA] Any new documentation only uses public API
The only function that was preventing ArrayPartitions of GPU arrays to work in DifferentialEquations solvers was `recursivefill!`, which was deferring to `Base.fill!` with scalar indexing. This PR makes fixes two things:
- `recursivefill!` calls `fill!` on each array within the `ArrayPartitions.x` tuple - which now defer to the right GPU kernels.
- Filling does not require index …
=> Make ArrayPartitions of GPU arrays work in DifferentialEquations solvers

src/vector_of_array.jl, test/downstream/symbol_indexing.jl, test/interface_tests.jl
Close https://github.com/SciML/SciMLBase.jl/issues/889
=> fix: fix DiffEqArray constructors ambiguity

ext/RecursiveArrayToolsStructArraysExt.jl, test/basic_indexing.jl
Addresses https://github.com/SciML/OrdinaryDiffEq.jl/issues/2625#issuecomment-2720056747
The issue is that `VectorOfArray` indexing will not mutate a `VectorOfArray{StructArray}` due to the way `StructArrays` treats assignment: https://juliaarrays.github.io/StructArrays.jl/stable/counterintuitive/#Modifying-a-field-of-a-struct-element. For example:
```julia
u = VectorOfArray(StructArray{MVector{1, Float64}}(ntuple(_ -> [1.0, 2.0], 1)))
u[1,1] = 100
@show u[1,1] # this is still 1.0
```
=> Specialize `setindex!` for `VectorOfArray{StructArray}`

ext/RecursiveArrayToolsStructArraysExt.jl, test/basic_indexing.jl
Attempt 2 to address https://github.com/SciML/OrdinaryDiffEq.jl/issues/2625#issuecomment-2720056747. I just applied the same approach taken in https://github.com/SciML/RecursiveArrayTools.jl/pull/425 for `setindex!` to broadcasted `Base.copyto!`.
I've verified that this also fixes the discrepancy in number of time-steps taken by an adaptive solver. The following MWE now results in the same number of accepted time-steps under this PR.
```julia
using OrdinaryDiffEqSSPRK, RecursiveArrayTools
using StaticArrays, StructArrays
function rhs!(du_voa, u_voa, params, t)
du = parent(du_voa)
u = parent(u_voa)
du .= u
end
u = StructArray{SVector{1, Float64}}(ntuple(_ -> [1.0, 2.0], 1))
ode = ODEProblem(rhs!, VectorOfArray(u), (0, 0.7))
sol_SA = solve(ode, SSPRK43())
@show sol_SA.stats.naccept
u = …
```
=> Fix broadcast assignment for `VectorOfArray` with `StructArrays`

src/named_array_partition.jl, src/utils.jl, src/vector_of_array.jl, test/downstream/symbol_indexing.jl, test/gpu/arraypartition_gpu.jl, test/named_array_partition_tests.jl
Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/430.
=> Use `similar` methods from `ArrayPartion` for `NamedArrayPartition`

src/vector_of_array.jl
Should fix https://buildkite.com/julialang/scimlsensitivity-dot-jl/builds/3324#0196626e-4fbc-4efa-887a-5d16f49ab679/459-1664
=> Make VectorOfArray adapt not broadcast the `to`

docs/pages.jl, docs/src/AbstractVectorOfArrayInterface.md, src/RecursiveArrayTools.jl, src/vector_of_array.jl
Noticed in https://github.com/SciML/Catalyst.jl/pull/1248, the linear indexing is actually fine when done on scalar arrays because that matches the linear indexing that you get from an AbstractArray interface. So instead the deprecations are made more precise to be just about the array of array case.
=> More precise deprecations of linear indexing and add an interface definition page

src/named_array_partition.jl, test/named_array_partition_tests.jl
New function implemented for ArrayInterface.zeromatrix for a NamedArrayPartition rather than an ArrayPartition in the style of commit 2094a78. Tests also implemented for both the return type and size of the zeromatrix. The implementation has been privately tested to work with OrdinaryDiffEq.jl and the implicit solvers that previously errored.
Created as a fix to https://github.com/SciML/OrdinaryDiffEq.jl/issues/2707
=> NamedArrayPartition zeromatrix

ext/RecursiveArrayToolsKernelAbstractions.jl, test/gpu/Project.toml, test/gpu/vectorofarray_gpu.jl
**What feature report was addressed?**
In order to select where a KernelAbstractions kernel is launched it is helpful to be able to query the corresponding backend.
For `VectorOfArrays` this is a little bit weird since we likely care about where the "inner" arrays are being stored.
**Checklist**
- [] Appropriate tests were added
- [] The new feature was added in a way that does not break public API
- [] New documentation related to the new feature was added
- [] The new code follows the
**Additional context**
=> Add KernelAbstractions.get_backend for VectorOfArray

README.md, src/array_partition.jl, src/named_array_partition.jl
closes https://github.com/SciML/RecursiveArrayTools.jl/issues/400
=> Improved performance of Broadcasting.

ext/RecursiveArrayToolsZygoteExt.jl, test/adjoints.jl
Seen in some places surfacing as
```julia
ERROR: MethodError: no method matching size(::@NamedTuple{u::Vector{Vector{Float64}}})
The function `size` exists, but no method is defined for this combination of argument types.
You may need to implement the `length` method or define `IteratorSize` for this type to be `SizeUnknown`.
Closest candidates are:
size(::IdentityOperator)
@ SciMLOperators ~/.julia/packages/SciMLOperators/Gd0Qg/src/basic.jl:21
size(::Graphs.DefaultDistance)
@ Graphs ~/.julia/packages/Graphs/awp48/src/distance.jl:22
size(::CSV.ReversedBuf)
@ CSV …
```
=> Add `literal_getproperty` disptach for `VectorOfArray`

src/RecursiveArrayTools.jl
Fixes markdown parsing issues in docstring from stray bacticks
=> Fix backticks and spacing in docstring
