src/array_partition.jl
test/utils_test.jl

This PR fixes https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/341

Fix the printing for Array of ArrayPartition

---

src/vector_of_array.jl
test/interface_tests.jl

Closes https://github.com/SciML/RecursiveArrayTools.jl/issues/77.

Constructors with all elements of the same type

---

src/zygote.jl

Adjoint for VecOfArray getindex

---

src/array_partition.jl
test/linalg.jl
test/partitions_test.jl

Added linalg mul! overloads for ArrayPartition with tests

---

src/array_partition.jl
test/upstream.jl

Fixes https://github.com/SciML/DifferentialEquations.jl/issues/679

fix ArrayPartition ZeroMatrix, i.e. stiff ODEs on recursive AP

---

src/zygote.jl

Fixes https://github.com/SciML/DiffEqSensitivity.jl/issues/339 and fixes https://github.com/SciML/DiffEqSensitivity.jl/issues/340.
@samuela

add literal getproperty adjoint to ArrayPartition

---

Project.toml
src/array_partition.jl
test/basic_indexing.jl

Fixes and tests https://github.com/SciML/RecursiveArrayTools.jl/issues/49

workaround Base changes for multi-indexing array partition

---

README.md
src/array_partition.jl
src/vector_of_array.jl

Stylistic revision, consistency, typos, etc.

Documentation changes

---

Project.toml
src/vector_of_array.jl
test/interface_tests.jl

In general, Base.collect_similar isn't able to figure out the right output

add a map overload

---

Project.toml
src/vector_of_array.jl

Found in https://github.com/SciML/DiffEqSensitivity.jl/pull/434/checks?check_run_id=2920157414#step:6:1426

Hotfix ambiguity

---

src/vector_of_array.jl

@ChrisRackauckas 
https://github.com/SciML/SciMLBase.jl/pull/66

Fix issymbollike

---

src/init.jl

Requires https://github.com/SciML/DiffEqSensitivity.jl/pull/575 kind of, but not really, it's just a small optimization

Cut out extra requires

---

Project.toml
src/array_partition.jl
test/gpu/ode_gpu.jl

Fixes https://discourse.julialang.org/t/results-of-secondorderodeproblem-give-error-this-object-is-not-a-gpu-array/82100

Fix ArrayPartition CuArray transformation

---

src/array_partition.jl
test/partitions_test.jl

This is useful for some of my use cases.

Add convert to ArrayPartition

---

src/vector_of_array.jl

fixes https://github.com/SciML/SciMLBase.jl/issues/275

add `Matrix` and `Vector` constructor where appropriate

---

src/vector_of_array.jl

Fixes https://github.com/SciML/RecursiveArrayTools.jl/issues/262

Fix typo in recipes to use symbol cache

---

Project.toml
ext/RecursiveArrayToolsMonteCarloMeasurementsExt.jl
test/downstream/Project.toml
test/downstream/measurements_and_units.jl

Fixes https://discourse.julialang.org/t/error-when-using-unitful-and-montecarlomeasurements-with-differentialequations/103464

Support nesting Unitful and MonteCarloMeasurements

---

src/array_partition.jl
test/partitions_test.jl

Fix `iszero`

---

src/vector_of_array.jl

[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [ScioML Style Guide](https://github.com/SciML/SciMLStyle) and

fix: remove extra comma

---

ext/RecursiveArrayToolsZygoteExt.jl
src/RecursiveArrayTools.jl

fix: GPU tests, CuArray conversion, autodiff

---

src/vector_of_array.jl
test/interface_tests.jl

fix: fix checkbounds, view methods, indexing, and add tests

---

test/basic_indexing.jl
test/interface_tests.jl

Needed for https://github.com/SciML/SymbolicIndexingInterface.jl/pull/29#issuecomment-1908001765.

Fix deprecation warnings

---

src/array_partition.jl
test/partitions_test.jl

fix: fix `Base.length` for empty `ArrayPartition`, add tests

---

test/downstream/symbol_indexing.jl

I've verified that tests pass locally

test: fix symbolic indexing adjoint test

---

src/vector_of_array.jl

Fixes https://github.com/SciML/DifferentialEquations.jl/issues/1050

Overload issingular for AbstractVectorOfArray
